workflows:
  macos-release:
    name: macOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        # Version will be read from pubspec.yaml
        FLUTTER_VERSION: "3.24.0"
        XCODE_VERSION: "15.4"
        COCOAPODS_VERSION: "1.15.2"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Set up signing certificate
        script: |
          app-store-connect fetch-signing-files app.flites.editor --type MAC_APP_STORE --create
      - name: Set up provisioning profile
        script: |
          app-store-connect fetch-signing-files app.flites.editor --type MAC_APP_STORE --create
      - name: Install Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build macOS app for App Store
        script: |
          flutter build macos --release --no-codesign
      - name: Code sign macOS app
        script: |
          codesign --force --options runtime --sign "$(APP_STORE_CONNECT_API_KEY_ID)" --entitlements apps/flites/macos/Runner/Release.entitlements apps/flites/build/macos/Build/Products/Release/flites.app
      - name: Create macOS app archive
        script: |
          cd apps/flites/build/macos/Build/Products/Release
          zip -r flites-macos.zip flites.app
    artifacts:
      - apps/flites/build/macos/Build/Products/Release/flites-macos.zip
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: true
