workflows:
  macos-release:
    name: macOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: flites_app_store_connect
    environment:
      vars:
        # Version will be read from pubspec.yaml
        FLUTTER_VERSION: "3.24.0"
        XCODE_VERSION: "15.4"
        COCOAPODS_VERSION: "1.15.2"
      groups:
        - production
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          set -e
          keychain initialize
      - name: Set up signing certificate
        script: |
          set -e
          app-store-connect fetch-signing-files app.flites.editor --type MAC_APP_STORE --create
      - name: Install Flutter dependencies
        script: |
          set -e
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          set -e
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          set -e
          flutter analyze
      - name: Flutter unit tests
        script: |
          set -e
          flutter test
      - name: Build macOS app for App Store
        script: |
          set -e
          flutter build macos --release --no-codesign
      - name: Code sign macOS app
        script: |
          set -e
          # Verify entitlements file exists
          if [ ! -f "apps/flites/macos/Runner/Release.entitlements" ]; then
            echo "Error: Release.entitlements file not found at apps/flites/macos/Runner/Release.entitlements"
            exit 1
          fi
          # Use the correct variable for signing identity
          codesign --force --options runtime --sign "$APP_STORE_CONNECT_KEY_IDENTIFIER" --entitlements apps/flites/macos/Runner/Release.entitlements apps/flites/build/macos/Build/Products/Release/flites.app
      - name: Create macOS app archive
        script: |
          set -e
          cd apps/flites/build/macos/Build/Products/Release
          zip -r flites-macos.zip flites.app
    artifacts:
      - apps/flites/build/macos/Build/Products/Release/flites-macos.zip
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: true
