#!/bin/bash

if [ ! -f util/.utils_root ]; then
    echo "Run this script from the root of the Flite repository"
    echo "I.e. util/pub_get_all"
    exit 1
fi

set -e

BASE=$(pwd)
OFFLINE_MODE=""
PUB_MODE="upgrade"
for arg in "$@"
do
  # Check for --offline parameter
  if [ "$arg" == "--offline" ]; then
      OFFLINE_MODE="--offline"
      echo "Running in offline mode"
  elif [ "$arg" == "--downgrade" ]; then
      PUB_MODE="downgrade"
      echo "Running in downgrade mode"
  fi
done

echo "PUB UPGRADE ALL"

declare -a dart_paths=(
  "."
)

declare -a flutter_paths=(
  "examples/auth_example/auth_example_flutter"
  "examples/chat/chat_flutter"
  "packages/serverpod_flutter"
  "templates/serverpod_templates/projectname_flutter"
  "modules/serverpod_auth/serverpod_auth_shared_flutter"
  "modules/serverpod_auth/serverpod_auth_apple_flutter"
  "modules/serverpod_auth/serverpod_auth_google_flutter"
  "modules/serverpod_auth/serverpod_auth_email_flutter"
  "modules/serverpod_auth/serverpod_auth_firebase_flutter"
  "modules/serverpod_chat/serverpod_chat_flutter"
  "tests/serverpod_test_flutter"
)

# Upgrade Dart packages
for path in "${dart_paths[@]}"; do
  echo "\n### $path"
  cd "$BASE/$path"
  dart pub $PUB_MODE $OFFLINE_MODE
done

# Upgrade Flutter packages
for path in "${flutter_paths[@]}"; do
  echo "\n### $path"
  cd "$BASE/$path"
  flutter pub $PUB_MODE $OFFLINE_MODE
done
