name: flites
description: "The free & open source sprite generator"
publish_to: "none"

version: 0.0.11

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  signals: ^6.2.0
  flutter_reorderable_grid_view: ^5.5.1
  image: ^4.5.4
  flutter_box_transform: ^0.4.7
  file_picker: ^10.3.3
  flutter_isolate: ^2.1.0
  path_provider: ^2.1.5
  menu_bar: ^0.5.3
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  pub_semver: ^2.2.0
  shared_preferences: ^2.5.3
  path: ^1.9.1
  file_saver: ^0.3.1
  flutter_dotenv: ^6.0.0
  syntax_highlight: ^0.5.0
  dart_casing: ^3.0.1
  markdown_widget: ^2.3.2+7
  desktop_drop: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/flites_logo.png"

  windows:
    generate: true
    image_path: "assets/images/flites_logo.png"
    icon_size: 256

  macos:
    generate: true
    image_path: "assets/images/flites_logo_macos.png"
