name: "PR Title is Conventional"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic_pull_request:
    name: ✅ Semantic Pull Request
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
  deploy_macos:
    name: 🍎 Build and Deploy macOS via codemagic.io
    uses: ./.github/workflows/macos_build.yaml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
